# Generated by Django 6.0.6 on 2026-06-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('online_count', models.IntegerField()),
                ('fault_count', models.IntegerField()),
                ('maintenance_count', models.IntegerField()),
                ('online_rate', models.FloatField()),
                ('fault_rate', models.FloatField()),
                ('analysis_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(max_length=128)),
                ('device_type', models.CharField(choices=[('camera', 'Camera'), ('sensor', 'Sensor')], max_length=20)),
                ('sub_type', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(choices=[('CORE_SCENIC', 'Core Scenic'), ('FIRE_ZONE', 'Fire Zone'), ('ENTRANCE_GATE', 'Entrance Gate'), ('INFRA_AREA', 'Infra Area'), ('TRAIL_ZONE', 'Trail Zone')], max_length=32)),
                ('install_date', models.DateField()),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('FAULT', 'Fault'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'), models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaultTimeRegionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('location', models.CharField(max_length=32)),
                ('fault_type', models.CharField(max_length=64)),
                ('fault_count', models.IntegerField()),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'unique_together': {('analysis_date', 'location', 'fault_type', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='FaultTypeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=64)),
                ('fault_count', models.IntegerField()),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('analysis_date', models.DateField()),
            ],
            options={
                'unique_together': {('fault_type', 'device_type', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=64)),
                ('fault_level', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('record_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['fault_type'], name='devices_dev_fault_t_a1196d_idx'), models.Index(fields=['record_time'], name='devices_dev_record__70695e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceHealthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.FloatField()),
                ('analysis_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['analysis_date'], name='devices_dev_analysi_a72c69_idx')],
                'unique_together': {('device', 'analysis_date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceWorkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField()),
                ('avg_cpu', models.FloatField()),
                ('avg_memory', models.FloatField()),
                ('avg_temperature', models.FloatField()),
                ('avg_power', models.FloatField()),
                ('avg_network_delay', models.FloatField()),
                ('health_score', models.FloatField()),
                ('analysis_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['stat_date'], name='devices_dev_stat_da_e2b67a_idx')],
                'unique_together': {('device', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('power', models.FloatField()),
                ('network_delay', models.FloatField()),
                ('uptime', models.FloatField()),
                ('record_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'record_time'], name='devices_dev_device__bafa6a_idx')],
            },
        ),
    ]
