# Generated by Django 6.0.6 on 2026-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faulttypedistribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faulttypedistribution',
            name='device_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='faulttypedistribution',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='faulttypedistribution',
            unique_together={('fault_type', 'device_type', 'location', 'analysis_date')},
        ),
        migrations.CreateModel(
            name='FaultTimeRegionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('location', models.CharField(max_length=32)),
                ('fault_type', models.CharField(max_length=64)),
                ('fault_count', models.IntegerField()),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'unique_together': {('analysis_date', 'location', 'fault_type', 'device_type')},
            },
        ),
        migrations.DeleteModel(
            name='DeviceWorstHealth',
        ),
    ]
