# Generated by Django 6.0.6 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulttimeregionanalysis',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faulttypedistribution',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='faulttimeregionanalysis',
            table='devices_faulttimeregionanalysis',
        ),
        migrations.AlterModelTable(
            name='faulttypedistribution',
            table='devices_faulttypedistribution',
        ),
    ]
