# Generated by Django 6.0.6 on 2026-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_faulttimeregionanalysis_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faulttimeregionanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faulttimeregionanalysis',
            name='fault_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='faulttimeregionanalysis',
            unique_together={('analysis_date', 'location', 'fault_type', 'device_type', 'fault_level')},
        ),
    ]
