"""
Django settings for forest_monitor project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ca9v9ytz112zk*1fpaf8mt0fyrm_fv!!_c-eb^%%x3m-&nyvqt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'sensor',
    'devices',
    'hdfs_app',
    'mapreduce_app',
    'ai_app',
    'visitor',
    'visual_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forest_monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR.parent / 'hdfs_app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forest_monitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'forest_monitor'),
        'USER': os.getenv('MYSQL_USER', 'root'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', '123456'),
        'HOST': os.getenv('MYSQL_HOST', '127.0.0.1'),
        'PORT': os.getenv('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Hadoop WebHDFS / MapReduce result
HDFS_WEB_HOST = 'hd0'
HDFS_WEB_PORT = 50070
HDFS_USER = 'root'
HDFS_OUTPUT_PATH = '/waether/output'
HDFS_PART_FILE = 'part-r-00000'
HDFS_TIMEOUT = 20
MAPREDUCE_TIMEOUT = 60 * 60

# Remote Hadoop runtime used by visitor/device MapReduce modules.
HADOOP_SSH_HOST = os.getenv('HADOOP_SSH_HOST', HDFS_WEB_HOST)
HADOOP_SSH_PORT = int(os.getenv('HADOOP_SSH_PORT', '22'))
HADOOP_SSH_USER = os.getenv('HADOOP_SSH_USER', HDFS_USER)
HADOOP_SSH_PASSWORD = os.getenv('HADOOP_SSH_PASSWORD', '')
HADOOP_SSH_KEY_FILENAME = os.getenv('HADOOP_SSH_KEY_FILENAME', '')
HADOOP_REMOTE_DIR = os.getenv('HADOOP_REMOTE_DIR', '/root/forest_monitor/hadoop')
HADOOP_REMOTE_DATASET_DIR = os.getenv(
    'HADOOP_REMOTE_DATASET_DIR',
    '/root/forest_monitor/datasets',
)
VISITOR_HDFS_INPUT_PATH = os.getenv('VISITOR_HDFS_INPUT_PATH', '/waether/visitor/input')
VISITOR_HDFS_OUTPUT_ROOT = os.getenv('VISITOR_HDFS_OUTPUT_ROOT', '/waether/visitor/output')
DEVICE_HDFS_BASE = os.getenv('DEVICE_HDFS_BASE', '/waether/devices')
