# Generated by Django 6.0.6 on 2026-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyComfortStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sample_count", models.PositiveIntegerField()),
                ("comfort_index_avg", models.FloatField()),
                ("comfortable_count", models.PositiveIntegerField()),
                ("attention_count", models.PositiveIntegerField()),
                ("uncomfortable_count", models.PositiveIntegerField()),
                ("comfort_rate", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="DailyRiskStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sample_count", models.PositiveIntegerField()),
                ("high_temp_count", models.PositiveIntegerField()),
                ("high_humidity_count", models.PositiveIntegerField()),
                ("pollution_count", models.PositiveIntegerField()),
                ("fire_risk_count", models.PositiveIntegerField()),
                ("normal_count", models.PositiveIntegerField()),
                ("risk_rate", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="DailyWeatherStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("temperature_avg", models.FloatField()),
                ("temperature_peak", models.FloatField()),
                ("humidity_avg", models.FloatField()),
                ("humidity_peak", models.FloatField()),
                ("pm25_avg", models.FloatField()),
                ("pm25_peak", models.FloatField()),
                ("illumination_avg", models.FloatField()),
                ("illumination_peak", models.FloatField()),
                ("risk_warning", models.CharField(default="正常", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HourlyWeatherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.PositiveSmallIntegerField(unique=True)),
                ("sample_count", models.PositiveIntegerField()),
                ("temperature_avg", models.FloatField()),
                ("humidity_avg", models.FloatField()),
                ("pm25_avg", models.FloatField()),
                ("illumination_avg", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["hour"],
            },
        ),
        migrations.CreateModel(
            name="MapReduceSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=32)),
                ("source_path", models.CharField(max_length=255)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="success", max_length=16)),
                ("message", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
