# Generated by Django 6.0.6 on 2026-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapreduce_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopRiskDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(unique=True)),
                ("date", models.DateField()),
                ("risk_score", models.FloatField()),
                ("dangerous_count", models.PositiveIntegerField()),
                ("temperature_peak", models.FloatField()),
                ("humidity_low", models.FloatField()),
                ("pm25_peak", models.FloatField()),
                ("illumination_peak", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
    ]
