# Generated by Django 6.0.6 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hdfs_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapreducerun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapreducerun",
            name="process_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
