# Generated by Django 6.0.6 on 2026-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyComfortStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sample_count', models.IntegerField()),
                ('comfort_index_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comfortable_count', models.IntegerField()),
                ('attention_count', models.IntegerField()),
                ('uncomfortable_count', models.IntegerField()),
                ('comfort_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRiskStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sample_count', models.IntegerField()),
                ('high_temp_count', models.IntegerField()),
                ('high_humidity_count', models.IntegerField()),
                ('pollution_count', models.IntegerField()),
                ('fire_risk_count', models.IntegerField()),
                ('normal_count', models.IntegerField()),
                ('risk_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DailyWeatherStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature_peak', models.DecimalField(decimal_places=1, max_digits=6)),
                ('humidity_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity_peak', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pm25_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm25_peak', models.DecimalField(decimal_places=1, max_digits=6)),
                ('illumination_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('illumination_peak', models.DecimalField(decimal_places=1, max_digits=10)),
                ('risk_warning', models.CharField(default='正常', max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HourlyWeatherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(unique=True)),
                ('sample_count', models.IntegerField()),
                ('temperature_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pm25_avg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('illumination_avg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='MapReduceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='TopRiskDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dangerous_count', models.IntegerField()),
                ('temperature_peak', models.DecimalField(decimal_places=1, max_digits=6)),
                ('humidity_low', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pm25_peak', models.DecimalField(decimal_places=1, max_digits=6)),
                ('illumination_peak', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
