# Generated by Django 4.2.10 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_time", models.DateTimeField(verbose_name="记录时间")),
                (
                    "entrance",
                    models.CharField(
                        choices=[
                            ("north", "北门"),
                            ("south", "南门"),
                            ("east", "东门"),
                            ("west", "西门"),
                            ("online", "线上预约"),
                        ],
                        max_length=20,
                        verbose_name="入口/来源点",
                    ),
                ),
                ("visitor_count", models.PositiveIntegerField(verbose_name="游客数量")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ticket", "售票闸机"),
                            ("camera", "视频识别"),
                            ("manual", "人工录入"),
                            ("api", "系统同步"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "weather",
                    models.CharField(blank=True, max_length=30, verbose_name="天气"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=120, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "游客流量记录",
                "verbose_name_plural": "游客流量记录",
                "ordering": ["-visit_time", "-id"],
                "indexes": [
                    models.Index(
                        fields=["visit_time"], name="visitor_vis_visit_t_891bfb_idx"
                    ),
                    models.Index(
                        fields=["entrance", "visit_time"],
                        name="visitor_vis_entranc_dbf278_idx",
                    ),
                ],
            },
        ),
    ]
