# Generated by Django 6.0.6 on 2026-06-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('total_count', models.IntegerField(verbose_name='当日游客总量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '每日游客统计',
                'verbose_name_plural': '每日游客统计',
                'db_table': 'visitor_daily_stat',
                'ordering': ['stat_date'],
                'indexes': [models.Index(fields=['stat_date'], name='visitor_dai_stat_da_5c39c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorGateStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=20, verbose_name='入口名称')),
                ('total_count', models.IntegerField(verbose_name='该入口累计游客数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '入口游客统计',
                'verbose_name_plural': '入口游客统计',
                'db_table': 'visitor_gate_stat',
                'ordering': ['-total_count'],
                'indexes': [models.Index(fields=['gate'], name='visitor_gat_gate_53a612_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorHourlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(verbose_name='小时')),
                ('total_count', models.IntegerField(verbose_name='该小时累计游客数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小时游客统计',
                'verbose_name_plural': '小时游客统计',
                'db_table': 'visitor_hourly_stat',
                'ordering': ['hour'],
                'indexes': [models.Index(fields=['hour'], name='visitor_hou_hour_c9e4d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(verbose_name='记录时间')),
                ('gate', models.CharField(choices=[('东门', '东门'), ('西门', '西门'), ('南门', '南门'), ('北门', '北门')], max_length=20, verbose_name='入口')),
                ('visitor_count', models.IntegerField(verbose_name='游客数量')),
                ('ticket_type', models.CharField(choices=[('成人票', '成人票'), ('学生票', '学生票'), ('团体票', '团体票'), ('老人票', '老人票')], max_length=20, verbose_name='票种')),
                ('weather', models.CharField(blank=True, max_length=30, verbose_name='天气')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '游客原始记录',
                'verbose_name_plural': '游客原始记录',
                'db_table': 'visitor_record',
                'ordering': ['-visit_time', '-id'],
                'indexes': [models.Index(fields=['visit_time'], name='visitor_rec_visit_t_033860_idx'), models.Index(fields=['gate', 'visit_time'], name='visitor_rec_gate_73efc5_idx')],
            },
        ),
    ]
